export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  ADD_SELECTED_PRODUCT: "ADD_SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  SET_FILTER: "SET_FILTER",
  SET_WISHLIST: "SET_WISHLIST",
  UPDATE_CHECKOUT_STATE: "UPDATE_CHECKOUT_STATE",
  UPDATE_CONTACT_INFO: "UPDATE_CONTACT_INFO",
  UPDATE_SHIPPING_METHOD: "UPDATE_SHIPPING_METHOD",
  UPDATE_PAYMENT_INFO: "UPDATE_PAYMENT_INFO"
};
